#!/bin/sh

set -o nounset \
    -o errexit

if [ $# -ne 0 ]; then
  echo "Loding environment varibles..."
  for var in "$@"
  do
    export "$var"
  done
fi

echo "Building application..."
# yarn install
yarn build

# echo Y | npm run-script build
# npm install -g serve

echo "Starting application..."
# yarn start
yarn start --mode production --port 3000
# serve -s /app/build -l tcp://0.0.0.0:3000
