export const SLACK_WALLBOARD_CHANNEL = "C8EUY86SH";
export const SLACK_REFLEX_CHANNEL = "C26TA1K6U";
export const SLACK_REPLICATION_CHANNEL = "CDTSS0YT1";
export const SLACK_GSR_DEV_CHANNEL = "C448GAXLH";
